/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaleReturnRouteImport } from './routes/sale-return'
import { Route as SaleOrderRouteImport } from './routes/sale-order'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PurchaseReturnRouteImport } from './routes/purchase-return'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductionEntryRouteImport } from './routes/production-entry'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as DeliveryNoteRouteImport } from './routes/delivery-note'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleReturnRoute = SaleReturnRouteImport.update({
  id: '/sale-return',
  path: '/sale-return',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleOrderRoute = SaleOrderRouteImport.update({
  id: '/sale-order',
  path: '/sale-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnRoute = PurchaseReturnRouteImport.update({
  id: '/purchase-return',
  path: '/purchase-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionEntryRoute = ProductionEntryRouteImport.update({
  id: '/production-entry',
  path: '/production-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryNoteRoute = DeliveryNoteRouteImport.update({
  id: '/delivery-note',
  path: '/delivery-note',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/delivery-note': typeof DeliveryNoteRoute
  '/estimates': typeof EstimatesRoute
  '/expenses': typeof ExpensesRoute
  '/funds': typeof FundsRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/production-entry': typeof ProductionEntryRoute
  '/products': typeof ProductsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchase-return': typeof PurchaseReturnRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sale-order': typeof SaleOrderRoute
  '/sale-return': typeof SaleReturnRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/team': typeof TeamRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/delivery-note': typeof DeliveryNoteRoute
  '/estimates': typeof EstimatesRoute
  '/expenses': typeof ExpensesRoute
  '/funds': typeof FundsRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/production-entry': typeof ProductionEntryRoute
  '/products': typeof ProductsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchase-return': typeof PurchaseReturnRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sale-order': typeof SaleOrderRoute
  '/sale-return': typeof SaleReturnRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/team': typeof TeamRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices': typeof InvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/delivery-note': typeof DeliveryNoteRoute
  '/estimates': typeof EstimatesRoute
  '/expenses': typeof ExpensesRoute
  '/funds': typeof FundsRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/production-entry': typeof ProductionEntryRoute
  '/products': typeof ProductsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchase-return': typeof PurchaseReturnRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sale-order': typeof SaleOrderRoute
  '/sale-return': typeof SaleReturnRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/team': typeof TeamRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/commissions'
    | '/customers'
    | '/delivery-note'
    | '/estimates'
    | '/expenses'
    | '/funds'
    | '/import'
    | '/inventory'
    | '/login'
    | '/payments'
    | '/production-entry'
    | '/products'
    | '/purchase-orders'
    | '/purchase-return'
    | '/purchases'
    | '/reports'
    | '/sale-order'
    | '/sale-return'
    | '/settings'
    | '/subscriptions'
    | '/team'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/commissions'
    | '/customers'
    | '/delivery-note'
    | '/estimates'
    | '/expenses'
    | '/funds'
    | '/import'
    | '/inventory'
    | '/login'
    | '/payments'
    | '/production-entry'
    | '/products'
    | '/purchase-orders'
    | '/purchase-return'
    | '/purchases'
    | '/reports'
    | '/sale-order'
    | '/sale-return'
    | '/settings'
    | '/subscriptions'
    | '/team'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/commissions'
    | '/customers'
    | '/delivery-note'
    | '/estimates'
    | '/expenses'
    | '/funds'
    | '/import'
    | '/inventory'
    | '/login'
    | '/payments'
    | '/production-entry'
    | '/products'
    | '/purchase-orders'
    | '/purchase-return'
    | '/purchases'
    | '/reports'
    | '/sale-order'
    | '/sale-return'
    | '/settings'
    | '/subscriptions'
    | '/team'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  CommissionsRoute: typeof CommissionsRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryNoteRoute: typeof DeliveryNoteRoute
  EstimatesRoute: typeof EstimatesRoute
  ExpensesRoute: typeof ExpensesRoute
  FundsRoute: typeof FundsRoute
  ImportRoute: typeof ImportRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductionEntryRoute: typeof ProductionEntryRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  PurchaseReturnRoute: typeof PurchaseReturnRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SaleOrderRoute: typeof SaleOrderRoute
  SaleReturnRoute: typeof SaleReturnRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TeamRoute: typeof TeamRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale-return': {
      id: '/sale-return'
      path: '/sale-return'
      fullPath: '/sale-return'
      preLoaderRoute: typeof SaleReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale-order': {
      id: '/sale-order'
      path: '/sale-order'
      fullPath: '/sale-order'
      preLoaderRoute: typeof SaleOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-return': {
      id: '/purchase-return'
      path: '/purchase-return'
      fullPath: '/purchase-return'
      preLoaderRoute: typeof PurchaseReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-entry': {
      id: '/production-entry'
      path: '/production-entry'
      fullPath: '/production-entry'
      preLoaderRoute: typeof ProductionEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-note': {
      id: '/delivery-note'
      path: '/delivery-note'
      fullPath: '/delivery-note'
      preLoaderRoute: typeof DeliveryNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  CommissionsRoute: CommissionsRoute,
  CustomersRoute: CustomersRoute,
  DeliveryNoteRoute: DeliveryNoteRoute,
  EstimatesRoute: EstimatesRoute,
  ExpensesRoute: ExpensesRoute,
  FundsRoute: FundsRoute,
  ImportRoute: ImportRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProductionEntryRoute: ProductionEntryRoute,
  ProductsRoute: ProductsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  PurchaseReturnRoute: PurchaseReturnRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SaleOrderRoute: SaleOrderRoute,
  SaleReturnRoute: SaleReturnRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TeamRoute: TeamRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
